# Generated by Django 2.2.12 on 2020-05-24 23:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_output_mmr_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='cuckoo_solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None),
        ),
    ]
